### PR TITLE
Team Page

### LINKED ISSUE #19: Team Page for Web Club Website
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Team) for further information.

### PR DESCRIPTION
**Pull request by pvgupta24**
Closes #19 
- [ ]  Header, footer files to be included
- [x]  Color changes
- [ ] Data required in team.json
- [x] Changes to make responsive.

screenshot from 2018-01-08 12-35-44

screenshot from 2018-01-08 12-36-02

### CODE REVIEW

**Comment by sbshah97** [comment]
@Hrily was this the final design? Doesn't really go with the rest of the pages!

**Comment by Hrily** [comment]
@salman-bhai 
You are right

I'll draft a new design for this...

**Comment by Hrily** [comment]
I've updated the design
Please check the issue #19

**Comment by pvgupta24** [comment]
team

**Comment by sbshah97** [comment]
What's the progress here, @pvgupta24 ? Are you done or work still pending?

**Comment by pvgupta24** [comment]
@salman-bhai , I'm making some changes.

**Comment by pvgupta24** [comment]
@salman-bhai  @Hrily , Please review.
## Desktop View
full
full2

## Mobile View
mob1
mob2

**Review by sbshah97 — APPROVED** [review]
Looks good to go from my end! @Hrily kindly review and merge if you approve!

**Review by Hrily — APPROVED** [review]

**Comment by Hrily** [comment]
@pvgupta24 
Please make icons black

image
And there seems to be a little gap between photo and the edges
Can you remove those?

Rest looks perfect...

**Comment by pvgupta24** [comment]
* @Hrily the gap is there because of some issues in my browser. works fine on mobile.
* Changed the icon colors.
mob

**Comment by Hrily** [comment]
I hope that I won't see it on my mobile
Anyways, merging this...

**Comment by pvgupta24** [comment]
@Hrily a little gap is there on both sides for mobile view. Was not looking good without it.

**Comment by Hrily** [comment]
@pvgupta24 
We'll see about this gap when we add actual photos

**Comment by Hrily** [comment]
@pvgupta24 
+ The hover color `red` on pink is looking bad. Make same color for all, maybe white will do.
+ The list at left does weird x-axis (left right) transition on hover, Can you somehow remove it?
+ And also make the transition time of hove as 0.1s

**Pull request merged**
