### PR TITLE
Projects Page

### LINKED ISSUE #18: Projects Page for Web Club Website
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Projects) for further information.

### PR DESCRIPTION
**Pull request by mishal23**
Closes #18 
Desktop View:

Mobile View:

### CODE REVIEW

**Review by sbshah97 — APPROVED** [review]
Looks good.  Amazing work.

**Comment by Hrily** [comment]
Following changes are needed:
+ "WE ARE WEB CLUB NITK" should be bold
+ Project listing should be like carousel, refer issue #18 for this.
+ 
image
Right margin is needed in mobile view for project description here

Rest is perfect 👍 
Good job

**Comment by sbshah97** [comment]
Any updates here, @mishal23 ?

**Comment by mishal23** [comment]
Working on it...
Will update the branch.

**Comment by sbshah97** [comment]
Alright please do this ASAP. We need to get this done as soon as possible!

**Comment by mishal23** [comment]
Sure @salman-bhai 
I'll try to finish this up by tonight.

**Comment by mishal23** [comment]
Following changes are made:
- "WE ARE WE WEBCLUB NITK" is made bold
-  Right margin is added for project description in mobile view
- Carousel listing made for projects
- Random background-color for each project every time - have added all the colours from [here](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Colors) for now (To add/remove colours to be as background, change only the colours array in /js/projects.js ) 

Screenshots to convey the same:
pr1
pr2
pr3
pr4

@salman-bhai @Hrily  Please review!

**Comment by sbshah97** [comment]
Looks good to go from me.

**Comment by Hrily** [comment]
image
Please don't keep this black

And don't keep title twice, once over the text box is fine

**Comment by mishal23** [comment]
@salman-bhai @Hrily done

**Comment by Hrily** [comment]
Okay 👍

**Comment by Hrily** [comment]
@mishal23 
+ By different background I meant different `BACKGROUND`, and not the color of box of project, keep the box white only. And change color of background
+ The background of 'On Going Projects' and color of 'Past Projects' can be gray

**Pull request merged**
