### PR TITLE
Team page: Transition and icon fixes

### PR DESCRIPTION
**Pull request by pvgupta24**
@Hrily  made the required changes mentioned in #27

### CODE REVIEW

**Comment by Hrily** [comment]
@pvgupta24 
The mobile view has width more than device width. Please fix this...

**Comment by pvgupta24** [comment]
@Hrily, I did not get you.

**Comment by Hrily** [comment]
image
The wiidth of the whole page is greater than the device width (you can see a horozontal scroll bar at the bottom)

**Comment by pvgupta24** [comment]
@Hrily made the required changes.
screenshot from 2018-01-11 19-19-40

**Comment by Hrily** [comment]
@pvgupta24 
Please make the team list width 100%. I mean remove the padding.
And also remove the scroll bar from the list, `overflow: visible` for mobile will do it I think.

**Comment by pvgupta24** [comment]
@Hrily  Please review.

**Pull request merged**
