### PR TITLE
All pdfs Shifted to one directory "slides"

### PR DESCRIPTION
**Pull request by ujdcodr**
This directory I have also placed in the Lecture-Repo. Please merge so I can link  the hrefs properly.

### CODE REVIEW

**Comment by sigsevneo** [comment]
Complete the linking. Mark the Issue resolved. Then we'll merge.

**Comment by ujdcodr** [comment]
ok boss

**Comment by ujdcodr** [comment]
Wait....I have to mark the issue as resolved??? Isn't that upto the person who raised the issue in the first place?

**Comment by ujdcodr** [comment]
closes #6

**Comment by ujdcodr** [comment]
fixes #6

**Pull request merged**
