### PR TITLE
Programming Contests page added

### LINKED ISSUE #20: Programming Contests Page for Web Club Website
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Contests) for further information.

### PR DESCRIPTION
**Pull request by omkarprabhu-98**
Closes #20

Desktop site (with placeholder data): 

contests

Mobile site (with placeholder data):

mcontests

### CODE REVIEW

**Review by sbshah97 — APPROVED** [review]
Looks good to go from my side!

**Comment by Hrily** [comment]
👍  From me too...

Just the padding in the mobile view of event is large
Make it small, half of current will do good.

Then I'll merge this...

**Comment by omkarprabhu-98** [comment]
Is this okay?

cmcontests

**Comment by Hrily** [comment]
@omkarprabhu-98 
I don't find any difference

I meant padding of event list if you are confused
The "Competitive Coding" in bold has large padding from the sides.

**Comment by omkarprabhu-98** [comment]
Sorry about that got confused between main title

Is this better?

nmcontests

**Comment by sbshah97** [comment]
All done here? Or are there any more changes left?

**Comment by omkarprabhu-98** [comment]
Waiting for @Hrily  to confirm changes,
Will commit changes after that.

**Comment by sbshah97** [comment]
@Hrily please review and merge this ASAP if there are no more changes to be done!

**Comment by Hrily** [comment]
@omkarprabhu-98 
Approved 👍

**Comment by sbshah97** [comment]
Abe closed nahi merge karna tha

**Comment by Hrily** [comment]
okay bhai

**Comment by omkarprabhu-98** [comment]
Final commit was remaining!

**Pull request merged**
