### PR TITLE
Fix Index Transitions

### PR DESCRIPTION
**Pull request by MJ10**
* Fix About Us text behaviour
* Fix section 3 -> section 2 transition

### CODE REVIEW

**Comment by Hrily** [comment]
Do not close this yet
Key bindings on index page are still under implementation

**Comment by MJ10** [comment]
@Hrily Added the key bindings, you can take a look now

**Comment by Hrily** [comment]
The same wierdness of 'About Us' is seen while transition of section 1 -> 2.
Can you solve this

**Comment by MJ10** [comment]
@Hrily should I create a new PR?

**Comment by Hrily** [comment]
yeah

**Pull request merged**
