### PR TITLE
modified member list, kick starting blogs

### PR DESCRIPTION
**Pull request by adeepkit01**

### CODE REVIEW

**Comment by chinmaydd** [comment]
@adeepkit01 Nice. Since your commit message says "kick starting blog", can we have an introductory blog post from the new convenor ? ;)

**Comment by adeepkit01** [comment]
@chinmaydd I will write something and will make everyone of you write too :P, but for now I think its perfect to start the blogs of a coding club with a tutorial on git (and github, home of many OSS)

**Comment by chinmaydd** [comment]
@adeepkit01 That sounds awesome! Go for it :smile:

**Comment by ani94** [comment]
Awesome 👍

**Pull request merged**
