### PR TITLE
Index Page

### LINKED ISSUE #16: Index.html page for new Web Club Website
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Index) for further information.

### PR DESCRIPTION
**Pull request by MJ10**
Closes #16 
Screenshots: 
## Desktop
screenshot from 2018-01-08 17-09-53
screenshot from 2018-01-08 17-09-59
screenshot from 2018-01-08 17-10-06

## Mobile
127 0 0 1-8000- galaxy s5
127 0 0 1-8000- galaxy s5 1

### CODE REVIEW

**Review by sbshah97 — APPROVED** [review]
Looks good from my side!

**Comment by Hrily** [comment]
Can you add screenshots here???

**Comment by MJ10** [comment]
@Hrily Added the screenshots, please take a look :)

**Comment by Hrily** [comment]
Great Job 👍 

Need to have a look on transitions

**Comment by sbshah97** [comment]
@Hrily are we done here? Or are there any more changes to be made?

**Comment by sbshah97** [comment]
@Hrily what about this?

**Comment by Hrily** [comment]
I need to clone this to see the transitions...

**Pull request merged**
