### PR TITLE
Create events page

### LINKED ISSUE #17: Events page for Web Club Website
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Events) for further information.

### PR DESCRIPTION
**Pull request by utkarsh23**
Closes #17 
# Desktop View
webclub_desktop
# Mobile View
webclub_mobile
**Do not merge this PR just yet.**
- [x] Create Basic Events Page
- [x] Sort events by date
- [x] Create modal for event description
- [x] Add transitions for modals

### CODE REVIEW

**Comment by sbshah97** [comment]
FOr fututre references, if you are still working on your PR, add a `WIP` in the PR Title!

**Comment by Hrily** [comment]
@utkarsh23 

+ A slight left margin for events on mobile view would be great.
+ Make title of the event description view bold
+ The background of Events was supposed to be Gray, @salman-bhai What do you say, should it be gray or image. I prefer gray.

The rest is perfect 👍 
Good Job

**Comment by sbshah97** [comment]
I prefer image @Hrily. Always looks better

**Comment by Hrily** [comment]
@salman-bhai 
Okay 👍

**Comment by Hrily** [comment]
@utkarsh23 
We need to have a Year scroller as well.
See Programming events PR for the design

**Comment by utkarsh23** [comment]
Alright 👍

**Comment by sbshah97** [comment]
@Hrily  anything else that's needed here?

**Review by sbshah97 — APPROVED** [review]
Looks good to go from my end! @Hrily please merge once you think the same as well!

**Comment by utkarsh23** [comment]
@salman-bhai just a few more changes, I'll try to wrap it up by tonight

**Comment by sbshah97** [comment]
Alright.

**Comment by utkarsh23** [comment]
Changes made, you can review this now

**Comment by sbshah97** [comment]
Looks good from my side, let's wait for @Hrily 's review!

**Comment by Hrily** [comment]
image
Please check the font size
Also remove the `Events` background color

**Pull request merged**
